"""Add otp_expires_at column to users table and increase otp_code to 6 chars.

Revision ID: g7h8i9j0k1l2
Revises: f1a2b3c4d5e6
Create Date: [TIMESTAMP]

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'g7h8i9j0k1l2'
down_revision = 'df4567890123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_expires_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('users', 'otp_code',
               existing_type=sa.String(length=4),
               type_=sa.String(length=6),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'otp_code',
               existing_type=sa.String(length=6),
               type_=sa.String(length=4),
               existing_nullable=True)
    op.drop_column('users', 'otp_expires_at')
    # ### end Alembic commands ###

