import httpx
import io
import os
import base64
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
from supabase import create_client, Client
from urllib.parse import quote
from typing import Optional
from sqlalchemy.orm import Session
from app.core.config import settings
from app.models.arrangement import Arrangement

class PollinationsService:
    def __init__(self):
        # 2026 Unified API Endpoint
        self.base_url = "https://gen.pollinations.ai/image/"
        self.model = "flux" # Or your preferred model like 'turbo'

    async def generate_arrangement_image(self, db: Session, arrangement_id: str, optimized_prompt: str):
        arrangement = db.query(Arrangement).filter(Arrangement.id == arrangement_id).first()
        if not arrangement:
            return None

        # Create safe, high-quality prompt constraints
        safe_prompt = f"{optimized_prompt}, elegant floral arrangement, professional photography, clean background, highly detailed, no people, no text, no watermarks, safe for work"
        encoded_prompt = quote(safe_prompt)
        clean_key = settings.POLLINATIONS_API_KEY.strip()
        pollinations_url = f"{self.base_url}{encoded_prompt}?width=1024&height=1024&model={self.model}&nologo=true&seed=42&key={clean_key}"

        # ==========================================
        # 1. POLLINATIONS TRY BLOCK
        # ==========================================
        try:
            async with httpx.AsyncClient() as client:
                resp = await client.get(pollinations_url, timeout=60.0)
                resp.raise_for_status()
                image_bytes = resp.content
        except Exception as e:
            print(f"❌ POLLINATIONS ERROR: {e}")
            return None

        # ==========================================
        # 2. IMAGE WATERMARKING (Logo + Text)
        # ==========================================
        img = Image.open(io.BytesIO(image_bytes)).convert("RGBA")
        
        # --- A. APPLY ESTING'S LOGO (Top-Left) ---
        try:
            # 🚀 THE FIX: Dynamically jump out of the backend folder and into the web folder
            current_dir = Path(__file__).resolve().parent # .../apps/backend/app/services
            apps_dir = current_dir.parent.parent.parent   # .../apps/
            
            # NOTE: If this fails with UnidentifiedImageError, change .svg to .png!
            logo_path = apps_dir / "web" / "public" / "EstingsLogo.svg"
            
            logo = Image.open(str(logo_path)).convert("RGBA")
            
            # Resize the logo so it's not too massive (150x150 max)
            logo.thumbnail((150, 150))
            
            # Paste the logo at (x: 20, y: 20). 
            img.paste(logo, (20, 20), logo)
        except Exception as e:
            print(f"⚠️ Warning: Could not apply Estings Logo. Path tried: {logo_path}")
            print(f"⚠️ Error Details: {e}")

        # --- B. APPLY TEXT WATERMARK (Bottom-Right) ---
        draw = ImageDraw.Draw(img)
        watermark_text = "Generated by Pollinations.ai | Esting's"
        
        # Scale font down slightly so long text fits
        font_size = max(30, img.width // 35) 
        try:
            font = ImageFont.truetype("arial.ttf", font_size)
        except:
            font = ImageFont.load_default()

        # Calculate bounding box to stick it in the bottom right corner
        bbox = draw.textbbox((0, 0), watermark_text, font=font)
        margin = 20
        x = img.width - (bbox[2] - bbox[0]) - margin
        y = img.height - (bbox[3] - bbox[1]) - margin

        # Draw a black shadow/outline for readability on bright flowers
        for dx, dy in [(-1,-1), (1,-1), (-1,1), (1,1)]:
            draw.text((x+dx, y+dy), watermark_text, fill="black", font=font)
            
        # Draw the actual text in semi-transparent white
        draw.text((x, y), watermark_text, fill=(255, 255, 255, 200), font=font)

        # Convert back to RGB to save as optimized PNG
        img = img.convert("RGB")
        output = io.BytesIO()
        img.save(output, format="PNG", optimize=True)
        watermarked_bytes = output.getvalue()

        # ==========================================
        # 3. SUPABASE TRY BLOCK
        # ==========================================
        try:
            supabase: Client = create_client(settings.SUPABASE_URL, settings.SUPABASE_SERVICE_KEY)
            file_path = f"{settings.SUPABASE_BUCKET}/{arrangement_id}.png"
            
            supabase.storage.from_(settings.SUPABASE_BUCKET).upload(
                path=file_path,
                file=watermarked_bytes,
                file_options={"content-type": "image/png", "x-upsert": "true"}
            )
            public_url = supabase.storage.from_(settings.SUPABASE_BUCKET).get_public_url(file_path)
            
            arrangement.generated_image_url = public_url
            db.commit()
            return public_url

        except Exception as e:
            print(f"❌ SUPABASE ERROR: {e}")
            return None