import type { RiderDelivery, RiderDeliveryOrder, RiderDeliveryStatus } from '@/services/deliveries-api';

export const previewDeliveries: RiderDelivery[] = [
  {
    address: 'San Fernando, Pampanga - near Capitol Boulevard',
    assignedArea: 'Pampanga',
    assignedVehicle: {
      brand: 'Honda',
      capacity: '3 floral arrangements',
      color: 'White',
      id: 'preview-vehicle-001',
      model: 'Click 125i',
      plateNumber: 'EFX 4821',
      vehicleType: 'Motorcycle',
    },
    branch: 'San Fernando',
    customerNotes: 'Recipient is available after lunch.',
    deliveredAt: null,
    deliveryNotes: 'Call when near the gate.',
    estimatedArrival: '2:30 PM',
    handlingNotes: ['Keep bouquet upright', 'Avoid direct sunlight'],
    id: 'preview-delivery-001',
    imageUrl: null,
    inTransitAt: null,
    itemSummary: 'Pink rose bouquet',
    orderId: 'preview-order-001',
    orderNumber: 'EST-1042',
    orderStatus: 'ready_for_delivery',
    pickedUpAt: null,
    proofNote: null,
    proofPhotoUrl: null,
    recipientName: 'Angela Reyes',
    recipientPhone: '09171234567',
    scheduledAt: new Date().toISOString(),
    status: 'assigned',
  },
  {
    address: 'Angeles City, Pampanga - Friendship Highway',
    assignedArea: 'Pampanga',
    assignedVehicle: {
      brand: 'Honda',
      capacity: '3 floral arrangements',
      color: 'White',
      id: 'preview-vehicle-001',
      model: 'Click 125i',
      plateNumber: 'EFX 4821',
      vehicleType: 'Motorcycle',
    },
    branch: 'San Fernando',
    customerNotes: 'Deliver to the front desk if the recipient is in a meeting.',
    deliveredAt: null,
    deliveryNotes: 'Leave with guard only after recipient confirms.',
    estimatedArrival: '3:15 PM',
    handlingNotes: ['Do not tilt arrangement'],
    id: 'preview-delivery-002',
    imageUrl: null,
    inTransitAt: null,
    itemSummary: 'Sunflower wrap',
    orderId: 'preview-order-002',
    orderNumber: 'EST-1043',
    orderStatus: 'ready_for_delivery',
    pickedUpAt: null,
    proofNote: null,
    proofPhotoUrl: null,
    recipientName: 'Marco Santos',
    recipientPhone: '09181234567',
    scheduledAt: new Date(Date.now() + 30 * 60 * 1000).toISOString(),
    status: 'assigned',
  },
  {
    address: 'Mabalacat, Pampanga - Dau terminal area',
    assignedArea: 'Pampanga',
    assignedVehicle: {
      brand: 'Honda',
      capacity: '3 floral arrangements',
      color: 'White',
      id: 'preview-vehicle-001',
      model: 'Click 125i',
      plateNumber: 'EFX 4821',
      vehicleType: 'Motorcycle',
    },
    branch: 'San Fernando',
    customerNotes: 'Sympathy flowers. Keep handoff quiet and respectful.',
    deliveredAt: null,
    deliveryNotes: 'Recipient asked for a call before arrival.',
    estimatedArrival: '4:00 PM',
    handlingNotes: ['Keep arrangement cool'],
    id: 'preview-delivery-003',
    imageUrl: null,
    inTransitAt: null,
    itemSummary: 'White sympathy basket',
    orderId: 'preview-order-003',
    orderNumber: 'EST-1044',
    orderStatus: 'ready_for_delivery',
    pickedUpAt: null,
    proofNote: null,
    proofPhotoUrl: null,
    recipientName: 'Carmela Dizon',
    recipientPhone: '09191234567',
    scheduledAt: new Date(Date.now() + 60 * 60 * 1000).toISOString(),
    status: 'assigned',
  },
];

export const previewDeliveryOrders: RiderDeliveryOrder[] = [
  {
    branch: 'San Fernando',
    createdAt: new Date().toISOString(),
    deliveries: previewDeliveries,
    deliveryOrderNumber: 'EDO-2026-001',
    id: 'preview-dispatch-001',
    notes: 'Reset demo batch: three paid orders ready for pickup and delivery.',
    riderId: 'preview-rider-001',
    riderName: 'Demo Rider',
    status: 'assigned',
    stopCount: previewDeliveries.length,
    updatedAt: new Date().toISOString(),
    vehicleId: 'preview-vehicle-001',
    vehiclePlateNumber: 'EFX 4821',
    vehicleType: 'Motorcycle',
  },
];

export function findPreviewDelivery(deliveryId: string) {
  return previewDeliveries.find((delivery) => delivery.id === deliveryId) ?? null;
}

export function updatePreviewDelivery(delivery: RiderDelivery, status: RiderDeliveryStatus): RiderDelivery {
  const timestamp = new Date().toISOString();

  return {
    ...delivery,
    arrivedAt: status === 'arrived' ? timestamp : delivery.arrivedAt,
    deliveredAt: status === 'delivered' ? timestamp : delivery.deliveredAt,
    inTransitAt: status === 'out_for_delivery' ? timestamp : delivery.inTransitAt,
    orderStatus: status === 'delivered' ? 'delivered' : status === 'out_for_delivery' ? 'out_for_delivery' : delivery.orderStatus,
    pickedUpAt: status === 'picked_up' ? timestamp : delivery.pickedUpAt,
    status,
  };
}
